# Generated by Django 3.2.9 on 2021-11-10 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empName', models.CharField(max_length=100)),
                ('empSurname', models.CharField(max_length=100)),
                ('compName', models.CharField(max_length=100)),
                ('budgetStatus', models.CharField(choices=[('300', 'smallTown'), ('500', 'cityCenter')], max_length=10)),
                ('active', models.CharField(choices=[('1', 'active'), ('2', 'terminated')], default=1, max_length=10)),
                ('balance', models.IntegerField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['empName'],
            },
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resName', models.CharField(max_length=100)),
                ('resAccount', models.IntegerField()),
            ],
            options={
                'db_table': 'restaurants',
                'ordering': ['resName'],
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compName', models.CharField(max_length=100)),
                ('compAccount', models.IntegerField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('employees', models.ManyToManyField(blank=True, related_name='employees', to='projects.Employees')),
                ('restaurants', models.ManyToManyField(blank=True, related_name='restaurants', to='projects.Restaurants')),
            ],
            options={
                'db_table': 'companies',
                'ordering': ['compName'],
            },
        ),
    ]
